services:
  db: 
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTRES_DB=${DB_NAME}
    container_name: postshirt
    volumes:
      - ./postgres:/var/lib/postgresql/data